# Generated by Django 4.1.5 on 2023-02-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Support",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "terms",
                    models.BooleanField(
                        default=False, verbose_name="took responsability"
                    ),
                ),
                ("message", models.TextField()),
                (
                    "person",
                    models.CharField(
                        choices=[("Employee", "Employee"), ("Candidate", "Candidate")],
                        max_length=60,
                    ),
                ),
                (
                    "option",
                    models.CharField(
                        choices=[
                            (
                                "Wanted to update my resume",
                                "Wanted to update my resume",
                            ),
                            ("I forgot my Password", "I forgot my Password"),
                            ("I forgot my account", "I forgot my account"),
                            ("Others", "Others"),
                        ],
                        max_length=60,
                    ),
                ),
                ("email", models.CharField(max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "situation",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Done", "Done")],
                        default="Pending",
                        max_length=60,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
