# Generated by Django 4.1.5 on 2023-02-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0003_alter_support_option_alter_support_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="support",
            name="email",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="support",
            name="option",
            field=models.CharField(
                choices=[
                    ("I lost my account", "I lost my account"),
                    ("My password does not work", "My password does not work"),
                    ("Update resume", "Update resume"),
                    ("Others", "Others"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="support",
            name="person",
            field=models.CharField(
                choices=[("Employee", "Employee"), ("Candidate", "Candidate")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="support",
            name="situation",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Done", "Done")],
                default="Pending",
                max_length=50,
                null=True,
            ),
        ),
    ]
