# Generated by Django 4.1.5 on 2023-02-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0004_alter_support_email_alter_support_option_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="support",
            name="option",
            field=models.CharField(
                choices=[
                    ("Wanted to update my resume", "Wanted to update my resume"),
                    ("Others", "Others"),
                    ("I forgot my account", "I forgot my account"),
                    ("I forgot my Password", "I forgot my Password"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="support",
            name="person",
            field=models.CharField(
                choices=[("Candidate", "Candidate"), ("Employee", "Employee")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="support",
            name="situation",
            field=models.CharField(
                choices=[("Done", "Done"), ("Pending", "Pending")],
                default="Pending",
                max_length=50,
                null=True,
            ),
        ),
    ]
