# Generated by Django 4.1.5 on 2023-02-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0005_alter_support_option_alter_support_person_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("message", models.TextField()),
                (
                    "situation",
                    models.CharField(
                        choices=[("Read", "Read"), ("Unread", "Unread")],
                        default="Unread",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="support",
            name="option",
            field=models.CharField(
                choices=[
                    ("I forgot my account", "I forgot my account"),
                    ("Others", "Others"),
                    ("I forgot my Password", "I forgot my Password"),
                    ("Wanted to update my resume", "Wanted to update my resume"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="support",
            name="person",
            field=models.CharField(
                choices=[("Employee", "Employee"), ("Candidate", "Candidate")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="support",
            name="situation",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Done", "Done")],
                default="Pending",
                max_length=50,
                null=True,
            ),
        ),
    ]
