# Generated by Django 4.1.5 on 2023-02-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0006_message_alter_support_option_alter_support_person_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notepad",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=70)),
                ("text", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="support",
            name="option",
            field=models.CharField(
                choices=[
                    ("Others", "Others"),
                    ("Wanted to update my resume", "Wanted to update my resume"),
                    ("I forgot my Password", "I forgot my Password"),
                    ("I forgot my account", "I forgot my account"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="support",
            name="situation",
            field=models.CharField(
                choices=[("Done", "Done"), ("Pending", "Pending")],
                default="Pending",
                max_length=50,
                null=True,
            ),
        ),
    ]
