# Generated by Django 4.1.5 on 2023-02-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0007_notepad_alter_support_option_alter_support_situation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Openings",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("backend", models.CharField(max_length=100)),
                ("frontend", models.CharField(max_length=100)),
                ("fullstack", models.CharField(max_length=100)),
                ("intern", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="support",
            name="option",
            field=models.CharField(
                choices=[
                    ("I forgot my account", "I forgot my account"),
                    ("I forgot my Password", "I forgot my Password"),
                    ("Wanted to update my resume", "Wanted to update my resume"),
                    ("Others", "Others"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="support",
            name="person",
            field=models.CharField(
                choices=[("Candidate", "Candidate"), ("Employee", "Employee")],
                max_length=50,
            ),
        ),
    ]
