# Generated by Django 4.1.5 on 2023-03-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0009_countdown_alter_support_option"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post",
                    models.CharField(
                        choices=[
                            ("Frontend", "Frontend"),
                            ("Backend", "Backend"),
                            ("Fullstack", "Fullstack"),
                            ("Intern", "Intern"),
                        ],
                        max_length=150,
                    ),
                ),
                ("email", models.EmailField(max_length=150)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "situation",
                    models.CharField(
                        choices=[("Unread", "Unread"), ("Read", "Read")],
                        default="unread",
                        max_length=75,
                        null=True,
                    ),
                ),
                ("document", models.FileField(upload_to="")),
                ("internal_note", models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name="message",
            name="situation",
            field=models.CharField(
                choices=[("Unread", "Unread"), ("Read", "Read")],
                default="Unread",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="support",
            name="option",
            field=models.CharField(
                choices=[
                    ("Wanted to update my resume", "Wanted to update my resume"),
                    ("Others", "Others"),
                    ("I forgot my Password", "I forgot my Password"),
                    ("I forgot my account", "I forgot my account"),
                ],
                max_length=50,
            ),
        ),
    ]
