# Generated by Django 4.1.5 on 2023-03-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0010_waitinglist_alter_message_situation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="situation",
            field=models.CharField(
                choices=[("Read", "Read"), ("Unread", "Unread")],
                default="Unread",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="support",
            name="option",
            field=models.CharField(
                choices=[
                    ("Wanted to update my resume", "Wanted to update my resume"),
                    ("Others", "Others"),
                    ("I forgot my account", "I forgot my account"),
                    ("I forgot my Password", "I forgot my Password"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="support",
            name="person",
            field=models.CharField(
                choices=[("Employee", "Employee"), ("Candidate", "Candidate")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="support",
            name="situation",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Done", "Done")],
                default="Pending",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="waitinglist",
            name="situation",
            field=models.CharField(
                choices=[("Read", "Read"), ("Unread", "Unread")],
                default="Unread",
                max_length=75,
                null=True,
            ),
        ),
    ]
