# Generated by Django 4.1.5 on 2023-03-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0011_alter_message_situation_alter_support_option_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="situation",
            field=models.CharField(
                choices=[("Unread", "Unread"), ("Read", "Read")],
                default="Unread",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="support",
            name="option",
            field=models.CharField(
                choices=[
                    ("Wanted to update my resume", "Wanted to update my resume"),
                    ("I forgot my account", "I forgot my account"),
                    ("Others", "Others"),
                    ("I forgot my Password", "I forgot my Password"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="support",
            name="person",
            field=models.CharField(
                choices=[("Candidate", "Candidate"), ("Employee", "Employee")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="support",
            name="situation",
            field=models.CharField(
                choices=[("Done", "Done"), ("Pending", "Pending")],
                default="Pending",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="waitinglist",
            name="email",
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name="waitinglist",
            name="situation",
            field=models.CharField(
                choices=[("Unread", "Unread"), ("Read", "Read")],
                default="Unread",
                max_length=75,
                null=True,
            ),
        ),
    ]
