# Generated by Django 4.1.5 on 2023-03-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0013_alter_countdown_options_alter_notepad_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="internal_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="support",
            name="internal_note",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="situation",
            field=models.CharField(
                choices=[("Read", "Read"), ("Unread", "Unread")],
                default="Unread",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="support",
            name="option",
            field=models.CharField(
                choices=[
                    ("I forgot my Password", "I forgot my Password"),
                    ("Others", "Others"),
                    ("I forgot my account", "I forgot my account"),
                    ("Wanted to update my resume", "Wanted to update my resume"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="waitinglist",
            name="situation",
            field=models.CharField(
                choices=[("Read", "Read"), ("Unread", "Unread")],
                default="Unread",
                max_length=75,
                null=True,
            ),
        ),
    ]
