# Generated by Django 4.1.5 on 2023-03-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0014_message_internal_note_support_internal_note_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacancies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataTarget", models.CharField(max_length=40)),
                ("title", models.CharField(max_length=100)),
                ("decription", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Vacancies",
            },
        ),
        migrations.AlterField(
            model_name="message",
            name="situation",
            field=models.CharField(
                choices=[("Unread", "Unread"), ("Read", "Read")],
                default="Unread",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="support",
            name="situation",
            field=models.CharField(
                choices=[("Done", "Done"), ("Pending", "Pending")],
                default="Pending",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="waitinglist",
            name="situation",
            field=models.CharField(
                choices=[("Unread", "Unread"), ("Read", "Read")],
                default="Unread",
                max_length=75,
                null=True,
            ),
        ),
    ]
