# Generated by Django 4.1.5 on 2023-03-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0015_vacancies_alter_message_situation_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vacancies",
            old_name="decription",
            new_name="description",
        ),
        migrations.AlterField(
            model_name="message",
            name="situation",
            field=models.CharField(
                choices=[("Read", "Read"), ("Unread", "Unread")],
                default="Unread",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="support",
            name="option",
            field=models.CharField(
                choices=[
                    ("I forgot my account", "I forgot my account"),
                    ("I forgot my Password", "I forgot my Password"),
                    ("Wanted to update my resume", "Wanted to update my resume"),
                    ("Others", "Others"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="waitinglist",
            name="situation",
            field=models.CharField(
                choices=[("Read", "Read"), ("Unread", "Unread")],
                default="Unread",
                max_length=75,
                null=True,
            ),
        ),
    ]
