# Generated by Django 4.1.5 on 2023-03-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0016_rename_decription_vacancies_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancies",
            name="section",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="support",
            name="option",
            field=models.CharField(
                choices=[
                    ("I forgot my Password", "I forgot my Password"),
                    ("I forgot my account", "I forgot my account"),
                    ("Others", "Others"),
                    ("Wanted to update my resume", "Wanted to update my resume"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="support",
            name="person",
            field=models.CharField(
                choices=[("Employee", "Employee"), ("Candidate", "Candidate")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="support",
            name="situation",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Done", "Done")],
                default="Pending",
                max_length=50,
                null=True,
            ),
        ),
    ]
