# Generated by Django 4.1.5 on 2023-04-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0018_remove_vacancies_section_alter_support_option_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="situation",
            field=models.CharField(
                choices=[("Unread", "Unread"), ("Read", "Read")],
                default="Unread",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="support",
            name="option",
            field=models.CharField(
                choices=[
                    ("Others", "Others"),
                    ("I forgot my Password", "I forgot my Password"),
                    ("Wanted to update my resume", "Wanted to update my resume"),
                    ("I forgot my account", "I forgot my account"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="support",
            name="situation",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Done", "Done")],
                default="Pending",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="waitinglist",
            name="situation",
            field=models.CharField(
                choices=[("Unread", "Unread"), ("Read", "Read")],
                default="Unread",
                max_length=75,
                null=True,
            ),
        ),
    ]
