# Generated by Django 4.1.5 on 2023-04-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0020_alter_support_option_alter_support_person_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="support",
            name="option",
            field=models.CharField(
                choices=[
                    ("I forgot my account", "I forgot my account"),
                    ("Wanted to update my resume", "Wanted to update my resume"),
                    ("Others", "Others"),
                    ("I forgot my Password", "I forgot my Password"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="support",
            name="person",
            field=models.CharField(
                choices=[("Employee", "Employee"), ("Candidate", "Candidate")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="support",
            name="situation",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Done", "Done")],
                default="Pending",
                max_length=50,
                null=True,
            ),
        ),
    ]
