# Generated by Django 4.1.5 on 2023-04-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0021_alter_support_option_alter_support_person_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="support",
            name="option",
            field=models.CharField(
                choices=[
                    ("Others", "Others"),
                    ("I forgot my Password", "I forgot my Password"),
                    ("I forgot my account", "I forgot my account"),
                    ("Wanted to update my resume", "Wanted to update my resume"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="support",
            name="situation",
            field=models.CharField(
                choices=[("Done", "Done"), ("Pending", "Pending")],
                default="Pending",
                max_length=50,
                null=True,
            ),
        ),
    ]
